school/apps/website/urls.py
from django.urls import path
from apps.website.views import (
    TeacherRegistrationView, TeacherLoginView, StudentListView,
    StudentDetailView, StudentDeleteView, StudentCreateView,
    SearchStudentsView, SendEmailView, EditStudentView
)

urlpatterns = [
    path('register/', TeacherRegistrationView.as_view(), name='register'),
    path('login/', TeacherLoginView.as_view(), name='login'),

    path('students/', StudentListView.as_view(), name='student_list'),
    path('students/<int:pk>/',
         StudentDetailView.as_view(), name='student_detail'),
    path('students/<int:pk>/edit/',
         EditStudentView.as_view(), name='edit_student'),
    path('students/<int:pk>/delete/',
         StudentDeleteView.as_view(), name='student_delete'),
    path('students/create/', StudentCreateView.as_view(), name='create_student'),

    path('search/', SearchStudentsView.as_view(), name='search_students'),

    path('send-email/', SendEmailView.as_view(), name='send_email'),
]

school/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.website.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

school/apps/website/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class School(models.Model):
    """
    Модель 'Школа'
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Class(models.Model):
    name = models.CharField(max_length=100)
    school = models.ForeignKey(
        School, on_delete=models.CASCADE, related_name='Class')

    def __str__(self):
        return self.name


class Teacher(AbstractUser):
    full_name = models.CharField(max_length=150)
    phone_number = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    class_group_student = models.ForeignKey(
        Class, on_delete=models.SET_NULL, null=True, related_name='teacher')

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='teachers',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        verbose_name='groups',
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='teachers',
        blank=True,
        help_text='Specific permissions for this user.',
        verbose_name='user permissions',
    )

    class Meta:
        verbose_name = 'Teacher'

    # USERNAME_FIELD = 'phone_number'
    # REQUIRED_FIELDS = []


class Student(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
    ]
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    birth_date = models.DateField()
    class_name = models.ForeignKey(
        Class, on_delete=models.CASCADE, related_name='student')
    address = models.CharField(max_length=100)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    photo = models.ImageField(upload_to='photos', blank=True, null=True)

    def __str__(self):
        return self.full_name

school/apps/website/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import Student, Class, Teacher


class StudentForm(forms.ModelForm):
    photo = forms.ImageField(required=False, label='Фотография')

    class Meta:
        model = Student
        fields = ['full_name', 'email', 'birth_date',
                  'class_name', 'address', 'gender', 'photo']


class EmailForm(forms.Form):
    subject = forms.CharField(max_length=100, label='Тема')
    message = forms.CharField(widget=forms.Textarea, label='Текст письма')


class TeacherRegistrationForm(forms.ModelForm):
    full_name = forms.CharField(max_length=150, label='ФИО')
    phone_number = forms.CharField(max_length=20, label='Номер телефона')
    subject = forms.CharField(max_length=100, label='Предмет')
    class_group_student = forms.ModelChoiceField(
        queryset=Class.objects.all(), label='Класс')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Повторите пароль', widget=forms.PasswordInput)

    class Meta(UserCreationForm.Meta):
        model = Teacher
        fields = ['username', 'full_name', 'phone_number', 'subject',
                  'class_group_student', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.full_name = self.cleaned_data['full_name']
        user.phone_number = self.cleaned_data['phone_number']
        user.subject = self.cleaned_data['subject']
        user.class_group_student = self.cleaned_data['class_group_student']

        password = self.cleaned_data['password1']
        user.set_password(password)

        if commit:
            user.save()
        return user


class PhoneNumberLoginForm(forms.Form):
    phone_number = forms.CharField(label='Номер телефона', max_length=20)
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)


class SearchForm(forms.Form):
    search_query = forms.CharField(label='Поиск', max_length=100)

school/apps/website/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import auth, messages
from django.db.models import Q

from config.settings import EMAIL_HOST_USER

from .models import Student
from .forms import (StudentForm, EmailForm,
                    TeacherRegistrationForm,
                    PhoneNumberLoginForm, SearchForm,)


class TeacherRegistrationView(View):
    def get(self, request):
        form = TeacherRegistrationForm()
        return render(request, 'registration.html', {'form': form})

    def post(self, request):
        form = TeacherRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('student_list')
        return render(request, 'registration.html', {'form': form})


class TeacherLoginView(View):
    def get(self, request):
        form = PhoneNumberLoginForm()
        return render(request, 'login.html', {'form': form})

    def post(self, request):
        form = PhoneNumberLoginForm(request.POST)

        phone_number = request.POST['phone_number']
        password = request.POST['password']
        user = auth.authenticate(
            request, phone_number=phone_number, password=password)
        if user:
            auth.login(request, user)
            messages.success(request, 'You are now logged in!')
            return redirect('student_list')
        else:
            return render(request, 'login.html', {'form': form})


class StudentListView(LoginRequiredMixin, View):
    def get(self, request):
        students = Student.objects.filter(
            class_name=request.user.class_group_student)
        return render(request, 'student_list.html', {'students': students})


class StudentDetailView(LoginRequiredMixin, View):
    def get(self, request, pk):
        student = get_object_or_404(Student, pk=pk)
        form = StudentForm(instance=student)
        return render(request, 'student_detail.html', {'student': student, 'form': form})

    # def post(self, request, pk):
        # student = get_object_or_404(Student, pk=pk)
        # form = StudentForm(request.POST, instance=student)
        # if form.is_valid():
        #     form.save()
        #     return redirect('student_list')
        # return render(request, 'student_detail.html', {'student': student, 'form': form})


class EditStudentView(LoginRequiredMixin, View):
    def get(self, request, pk):
        student = get_object_or_404(Student, pk=pk)
        form = StudentForm(instance=student)
        return render(request, 'edit_student.html', {'student': student, 'form': form})

    def post(self, request, pk):
        student = get_object_or_404(Student, pk=pk)
        form = StudentForm(request.POST, request.FILES, instance=student)
        if form.is_valid():
            form.save()
            return redirect('student_detail', pk=pk)
        return render(request, 'edit_student.html', {'student': student, 'form': form})


class StudentDeleteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        student = get_object_or_404(Student, pk=pk)
        student.delete()
        return redirect('student_list')


class StudentCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = StudentForm()
        return render(request, 'create_student.html', {'form': form})

    def post(self, request):
        form = StudentForm(request.POST, request.FILES)
        if form.is_valid():
            email = form.cleaned_data['email']
            if Student.objects.filter(email=email).exists():
                form.add_error(
                    'email', 'Ученик с таким адресом электронной почты уже существует.')
            else:
                student = form.save()

                school = student.class_name.school
                class_name = student.class_name.name
                teacher = student.class_name.teacher

                subject = f'Добро пожаловать в школу {school}'
                message = f'Дорогой {student.full_name},\n\nДобро пожаловать в нашу школу {school}!'
                message += f'Вы были добавлены в класс {class_name} под руководством учителя {teacher}.'
                from_email = EMAIL_HOST_USER
                to_email = student.email
                send_mail(subject, message, from_email, [to_email])

                return redirect('student_list')
        return render(request, 'create_student.html', {'form': form})


class SearchStudentsView(LoginRequiredMixin, View):
    def get(self, request):
        form = SearchForm()
        return render(request, 'search_students.html', {'form': form})

    def post(self, request):
        form = SearchForm(request.POST)
        if form.is_valid():
            search_query = form.cleaned_data['search_query']
            results = Student.objects.filter(
                Q(full_name__icontains=search_query) | Q(email__icontains=search_query))
            return render(request, 'search_results.html', {'form': form, 'results': results})
        return render(request, 'search_results.html', {'form': form})


class SendEmailView(LoginRequiredMixin, View):
    def get(self, request):
        form = EmailForm()
        return render(request, 'send_email.html', {'form': form})

    def post(self, request):
        form = EmailForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            students = Student.objects.filter(
                class_name=request.user.class_group_student)
            emails = [student.email for student in students]
            send_mail(subject, message, EMAIL_HOST_USER, emails)
            return redirect('student_list')
        return render(request, 'send_email.html', {'form': form})

school/apps/website/templates/create_student.html
{% extends 'base.html' %}

{% block content %}

    <div class="header">
        <h1>Create Form</h1>
    </div>

    <div class="form-container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="id_full_name">Full Name:</label>
            {{ form.full_name }}

            <label for="id_email">Email:</label>
            {{ form.email }}
            {% if form.errors.email %}
                <p class="error">{{ form.errors.email }}</p>
            {% endif %}

            <label for="id_birth_date">Birth Date:</label>
            {{ form.birth_date }}

            <label for="id_class_name">Class Name:</label>
            {{ form.class_name }}

            <label for="id_address">Address:</label>
            {{ form.address }}

            <label for="id_gender">Gender:</label>
            {{ form.gender }}

            <label for="id_photo">Photo:</label>
            {{ form.photo }}

            

            <button type="submit">Create</button>
        </form>
    </div>
    {% endblock %}

school/apps/website/templates/edit_student.html
{% extends 'base.html' %}

{% block content %}
  <h1>Редактирование ученика</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

school/apps/website/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <style>
        .header {
            background-color: #f2f2f2;
            padding: 20px;
            text-align: center;
        }

        .form-container {
            width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f2f2f2;
        }

        .form-container label {
            display: block;
            margin-bottom: 10px;
        }

        .form-container input[type="text"],
        .form-container input[type="password"] {
            width: 100%;
            padding: 8px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .form-container button[type="submit"], 
        .form-container button[type="submit"] a {
            background-color: #333;
            color: #fff;
            padding: 8px 16px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        
    </style>
</head>
<body>
    <div class="header">
        <h1>Login</h1>
    </div>
    <div class="form-container">
        <form method="post">
            {% csrf_token %}
            <label for="id_phone_number">Номер телефонв:</label>
            <input type="text" id="id_phone_number" name="phone_number" required>
        
            <label for="id_password">Пароль:</label>
            <input type="password" id="id_password" name="password" required>
        
            <button type="submit">Вход</button>
        </form>

        <button type="submit">
        <a href="{% url 'register'%}">Регистрация</a>
        </button>
        {% if error_message %}
        <p class="error-message">{{ error_message }}</p>
        {% endif %}
    </div>
    
   
</body>
</html>

school/apps/website/templates/registration.html
<!DOCTYPE html>
<html>
<head>
    <title>Регистрация</title>
    <style>
        .header {
            background-color: #f2f2f2;
            padding: 20px;
            text-align: center;
        }

        .form-container {
            width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f2f2f2;
        }

        .form-container label {
            display: block;
            margin-bottom: 10px;
        }

        .form-container input[type="text"],
        .form-container input[type="password"],
        .form-container select {
            width: 100%;
            padding: 8px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .form-container button[type="submit"] {
            background-color: #333;
            color: #fff;
            padding: 8px 16px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Регистрация учителя</h1>
    </div>

    <div class="form-container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">Зарегистрироваться</button>
        </form>
    </div>
</body>
</html>

school/apps/website/templates/search_results.html
{% extends 'base.html' %}

{% block content %}
    <title>Search Results</title>
    <style>
        .header {
            background-color: #f2f2f2;
            padding: 20px;
            text-align: center;
        }

        .search-results {
            margin-top: 20px;
        }

        .search-results h2 {
            margin-bottom: 10px;
        }

        .students-table {
            width: 100%;
            border-collapse: collapse;
        }

        .students-table th,
        .students-table td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        .students-table th {
            background-color: #f2f2f2;
        }

        .students-table tbody tr:hover {
            background-color: #f5f5f5;
        }
    </style>




    <div class="search-results">
        <h2>Результаты поиска:</h2>
        <table class="students-table">
            <thead>
                <tr>
                    <th>ФИО</th>
                    <th>Email</th>
                    <th>Дата рождения</th>
                    <th>Класс</th>
                    <th>Адрес</th>
                    <th>Пол</th>
                </tr>
            </thead>
            <tbody>
                {% for student in results %}
                <tr onclick="window.location.href='{% url 'student_detail' student.pk %}';">
                    <td>{{ student.full_name }}</td>
                    <td>{{ student.email }}</td>
                    <td>{{ student.birth_date }}</td>
                    <td>{{ student.class_name }}</td>
                    <td>{{ student.address }}</td>
                    <td>{{ student.gender }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6">Нет такого ученика</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% endblock %}

school/apps/website/templates/send_email.html
{% extends 'base.html' %}

{% block content %}
    <title>Students Send message</title>
    <style>
        .header {
            background-color: #f2f2f2;
            padding: 20px;
            text-align: center;
        }

        .form-container {
            width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f2f2f2;
        }

        .form-container label {
            display: block;
            margin-bottom: 10px;
        }

        .form-container input[type="text"],
        .form-container input[type="email"],
        .form-container select {
            width: 100%;
            padding: 8px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .form-container button[type="submit"] {
            background-color: #333;
            color: #fff;
            padding: 8px 16px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
    </style>

    <h1>Рассылка</h1>
    <form method="post" action="{% url 'send_email' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
    {% endblock %}

school/apps/website/templates/student_detail.html
{% extends 'base.html' %}

{% block content %}
{% csrf_token %}
  <h1>Инфорация об ученике</h1>
  <p>ФИО: {{ student.full_name }}</p>
  <p>Email: {{ student.email }}</p>
  <p>Дата рождения: {{ student.birth_date }}</p>
  <p>Класс: {{ student.class_name }}</p>
  <p>Адрес: {{ student.address }}</p>
  <p>Пол: {{ student.get_gender_display }}</p>
  {% if student.photo %}
  <p>Фотография <img src="{{ student.photo.url }}" alt="{{ student.full_name }}" width="200"></p>
{% else %}
  <p>Нет фотографии</p>
{% endif %}

<form action="{% url 'edit_student' student.pk %}" method="get">
  <input type="submit" value="Редактировать">
</form>

<button onclick="confirmDelete()">Удалить</button>

  <script>
    function confirmDelete() {
      if (confirm('Вы уверены, что хотите удалить этого студента?')) {
        document.getElementById('delete-form').submit();
      }
    }
  </script>

  <form id="delete-form" method="POST" action="{% url 'student_delete' student.pk %}">
    {% csrf_token %}
    <input type="hidden" name="_method" value="DELETE">
  </form>
{% endblock %}

school/apps/website/templates/student_list.html
{% extends 'base.html' %}

{% block content %}
   
    <div class="header">
        <h1>Список учеников</h1>
    </div>

    <table class="students-table">
        <thead>
            <tr>
                <th>ФИО</th>
                <th>Email</th>
                <th>Дата рождения</th>
                <th>Класс</th>
                <th>Адрес</th>
                <th>Пол</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
            <tr onclick="window.location.href='{% url 'student_detail' student.pk %}';">
                <td>{{ student.full_name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.birth_date }}</td>
                <td>{{ student.class_name }}</td>
                <td>{{ student.address }}</td>
                <td>{{ student.gender }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


    {% endblock %}